name: Build and Release Docker Image

on:
  push:
    branches:
      - release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t reddit-post-notifier:latest .

    - name: Save Docker Image as Tarball
      run: |
        docker save reddit-post-notifier:latest -o reddit-post-notifier.tar

    - name: Create GitHub Release and Upload Tarball
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Tarball to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./reddit-post-notifier.tar
        asset_name: reddit-post-notifier.tar
        asset_content_type: application/x-tar
